#!/usr/bin/env bash

dwsh() {
    local url="$1"
    local target="$2"
    local error=''
    
    [[ -z "$url" ]] && cerr "<error>[error]</> <g>you must specify the <i>download url" && return 1
    [[ -z "$target" ]] && cerr "<error>[error]</> <g>you must specify the <i>target path" && return 1
    [[ -d "$target" ]] && cerr "<error>[error]</> <g>the target path cant be a <i>directory" && return 1

    { error=$(curl -fL "$url" -o "$target" 2>&1 1>&3 | tee /dev/fd/3 | grep "^curl:"); } 3>&1
    [[ -n "$error" ]] && {
        echo -en "\033[1A"
        cerr "<error>[error]</> ->$(cut -d ':' -f2- <<< "$error")"
        return 1
    }
    
    chmod +x "$target"
    cerr "<g>✓ downloaded on <file>$target</>!"
}

(return 2>/dev/null) || { 
    . "$HOME/.fx/bash/config/develop/colors.bash"
    dwsh "$@";
}
