#!/usr/bin/env bash


update-hopp() {
    local url='https://github.com/hoppscotch/agent-releases/releases/latest/download/Hoppscotch_Agent_linux_x64.AppImage'
    local file="$HOME/apps/hopp.agent"

    "$FX_SCRIPTS/dwsh" "$url" "$file"
}

(return 2>/dev/null) || { 
    . "$HOME/.fx/bash/config/develop/colors.bash"
    update-hopp; 
}
