# echo -e "  ■■        ■▀■   "
# echo -e " ■  ■      ■   ■  "
# echo -e " ■  ■     ■     ■  > $(uname -n)"
# echo -e "  ■ ■       ■   ■ "
# echo -e "    ■ ■▀■   ■   ■ "
# echo -e "   ■ ■   ■   ■ ■  "
# echo -e "  ■   ■   ■▄■ ■   "
# echo -e "  ■   ■       ■ ■ "
# echo -e "  ■     ■     ■  ■"
# echo -e "   ■   ■      ■  ■"
# echo -e "    ■▄■        ■■ "
# echo -e "                  "