# echo -e "  ■■        ■▀■   "
# echo -e " ■  ■      ■   ■  "
# echo -e " ■  ■     ■     ■  > $(uname -n)"
# echo -e "  ■ ■       ■   ■ "
# echo -e "    ■ ■▀■   ■   ■ "
# echo -e "   ■ ■   ■   ■ ■  "
# echo -e "  ■   ■   ■▄■ ■   "
# echo -e "  ■   ■       ■ ■ "
# echo -e "  ■     ■     ■  ■"
# echo -e "   ■   ■      ■  ■"
# echo -e "    ■▄■        ■■ "
# echo -e "                  "

echo -e "\e[36m"
echo "  ∕⁀⧵             "
echo "  \ ∕        ∕⁀⧵  "
echo "   X            | "
echo "  / \ ∕⁀⧵   |   | "
echo " |   |   ⧵‿∕ \ /  "
echo " |            X   "
echo "  ⧵‿∕        ∕ \  "
echo "             ⧵‿∕  "
