# echo -e "  ■■        ■▀■   "
# echo -e " ■  ■      ■   ■  "
# echo -e " ■  ■     ■     ■  > $(uname -n)"
# echo -e "  ■ ■       ■   ■ "
# echo -e "    ■ ■▀■   ■   ■ "
# echo -e "   ■ ■   ■   ■ ■  "
# echo -e "  ■   ■   ■▄■ ■   "
# echo -e "  ■   ■       ■ ■ "
# echo -e "  ■     ■     ■  ■"
# echo -e "   ■   ■      ■  ■"
# echo -e "    ■▄■        ■■ "
# echo -e "                  "

if [ -z "${ZED}" ] || [ "${ZED}" != "1" ]; then
    echo -e "\e[36m"
    echo "  ∕⁀⧵             "
    echo "  \ ∕        ∕⁀⧵  "
    echo "   X            | "
    echo "  / \ ∕⁀⧵   |   | "
    echo " |   |   ⧵‿∕ \ /  "
    echo " |            X   "
    echo "  ⧵‿∕        ∕ \  "
    echo "             ⧵‿∕  "
fi